In [1]:
import cv2

In [ ]:
#face recognition in pictures

In [2]:
face_cascade=cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_default.xml')
img=cv2.imread("add your image",1)

In [3]:
gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [4]:
faces=face_cascade.detectMultiScale(gray_img, scaleFactor=1.05, minNeighbors=5)

In [5]:
print(type(faces))
print(faces)
for x,y,w,h in faces:
    img=cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)

<class 'numpy.ndarray'>
[[1733 1868   34   34]
 [1645 1966   28   28]
 [ 991  524  609  609]
 [1729  724  538  538]
 [1669 1935   68   68]
 [1282 1821  127  127]
 [ 760 1495   58   58]
 [1276 1563   70   70]
 [ 731 1644   97   97]
 [ 711 1604   55   55]
 [1077 2277   73   73]]


In [6]:
resized=cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0])))

In [7]:
cv2.imshow("Gray",resized)

In [8]:
cv2.waitKey(0)

-1

In [ ]:
#Image capture through web cam

In [9]:
import cv2,time
video=cv2.VideoCapture(0)
check,frame=video.read()
print(check)
print(frame)

time.sleep(5)
cv2.imshow("Capture",frame)

cv2.waitKey(0)
video.release()
cv2.destroyAllWindows()

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 18  76 132]
  [ 21  78 119]
  [ 19  76 116]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 16  76 132]
  [ 18  76 123]
  [ 16  73 120]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 15  73 129]
  [ 16  72 124]
  [ 15  71 123]]

 ...

 [[ 54  92 127]
  [ 54  92 127]
  [ 57  90 126]
  ...
  [  9  67 110]
  [ 12  68 111]
  [ 12  68 111]]

 [[ 54  91 129]
  [ 54  91 129]
  [ 56  89 125]
  ...
  [  9  67 112]
  [ 15  67 110]
  [ 15  67 110]]

 [[ 58  94 134]
  [ 58  94 134]
  [ 57  90 126]
  ...
  [  9  64 111]
  [ 13  64 107]
  [ 14  66 109]]]


In [10]:
#face recognition through live camera

In [ ]:
import cv2
cap=cv2.VideoCapture(0)
face_cascade=cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_default.xml')


while(True):
    ret,img=cap.read()
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=face_cascade.detectMultiScale(gray,1.3,5)
    for(x,y,w,h) in face:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,0),2)
    cv2.imshow("img",img)
    k=cv2.waitKey(10)
    if k==27:
        break
cap.release()
cv2.destroyAllWindows()